### ISSUE TITLE
Soil is a commercial plugin

### ISSUE THREAD

**Issue by retlehs** [wordplate/wordplate#138]
if you're going to have soil as a dependency then please add a note somewhere in the README + https://github.com/wordplate/wordplate/blob/master/public/themes/wordplate/library/plate-soil.php that mentions soil is a commercial plugin along with a link to https://roots.io/plugins/soil/

**Comment by vinkla** [comment]
Soil is released under MIT? https://github.com/roots/soil/blob/master/LICENSE.md

**Comment by retlehs** [comment]
it's still a commercial plugin. most commercial wordpress plugins have open source licenses.

**Comment by vinkla** [comment]
I can remove it entirely if you want me too.

**Comment by vinkla** [comment]
I also strongly advise you to update the license and move away from MIT

> Permission is hereby granted, **free of charge**, to any person obtaining a copy of this software and associated documentation

**Comment by retlehs** [comment]
would prefer that you remove it. we would include it by default in bedrock if it wasn't a commercial plugin. 

wordpress plugins have to be GPL compatible (even commercial ones), and all of those licenses are going to have similar language — don't really have a choice

**Comment by vinkla** [comment]
Okay, I'll remove it.

**Comment by Foxaii** [comment]
In its most simplistic, not offering any legal advice here, terms, the GPLv2 requires any PHP code to be released under the GPLv2 or later or a GPL compatible license if the code: 

1. relies on WordPress to operate (i.e. the code is a derivative work), and;
2. the code is being distributed (propagated).

This essentially describes all WordPress themes and plugins that use WordPress functions.

**Comment by magnus-bergman** [comment]
I'm sure everyone who uses soil (with wordplate or without) greatly appreciate the functionality and simplicity it provides, and roots should by all means get the compensation it deserves by having authored the code. But since it is open source, and licensed as such, there's no legal rights that can claim wordplate from removing it as a dependency.

I'm positive that people who use wordplate for commercial work are willing to pay 18$ per site to get soil in the package.

I suggest adding something to the wordplate readme in the lines of "Wordplate uses soil, if you like soil we encourage you to buy it."

Keeping soil in the wordplate repo will only increase the number of soil users and in affect, profit to roots. The few people who are greedy and refuse to pay the fee will still be able to just get it from github/packagist.

**Comment by vinkla** [comment]
Totally agree with @magnus-bergman. The Soil plugin is great and I don't see why we should exclude it. I'll add a link in the description.

**Comment by vinkla** [comment]
It is now added to the documentation.
