### ISSUE TITLE
Issue with WP-CLI

### ISSUE THREAD

**Issue by vinkla** [wordplate/wordplate#169]
As pointed out by @tditlu WP-CLI doesn't seem to work with the latest changes to the `wp-config.php` file. We've found a solution by including the `wp-settings.php` file in the `wp-config.php` file. More information here: [How to use wp-cli with a non-standard wp-config.php location](https://gist.github.com/samstoller/efc38eb309e62df392ea)

Does anyone else have a fix for this? Maybe @puredazzle @aaemnnosttv?

**Comment by aaemnnosttv** [comment]
I dug into this a bit.

The first problem is the error WP-CLI gives from not finding a line that loads `wp-settings.php`.
Since this is being loaded from `Application->run()` we can trick WP-CLI to make it happy by adding this to the bottom of the `wp-config.php`

```
/*
require wp-settings.php;
*/
```

The next problem has to do with `wp-settings.php` getting loaded more than once because WP-CLI adds this after it scrapes the code from the `wp-config.php` (less the line which loads `wp-settings.php`).

So we need to prevent loading `wp-settings.php` from the `run` method for WP-CLI requests.

Wrap the require in the `run` method like so:

```php
        // Sets up WordPress vars and included files.
        if (!defined('WP_CLI')) {
            require sprintf('%swp-settings.php', ABSPATH);
        }
```

The last and final problem I ran into was WP complaining that `$table_prefix` is undefined.

This is a problem because of the way `wp-settings.php` references `$table_prefix` as a local variable that it expects to be set before the file is required.

For this reason, `$table_prefix` needs to be defined in `wp-config.php`.

Moving this from the `run` method to `wp-config.php` after the autoloader is loaded fixes everything.

```php
// Set the WordPress database table prefix.
extract(['table_prefix' => env('WP_PREFIX', 'wp_')]);
```

The above conditional for loading `wp-settings.php` could be removed by moving that line to `wp-config.php` as well.  Kind of a bummer, but such is the world of WP.

**Comment by vinkla** [comment]
@aaemnnosttv thanks for taking the time to help out. I'll test that and push a new fix.

**Comment by tditlu** [comment]
Great minds think alike:
https://github.com/wordplate/wordplate/pull/170#event-1046422889
https://github.com/wordplate/framework/pull/41#event-1046423017

**Comment by vinkla** [comment]
@tditlu @aaemnnosttv I've pushed new changes to both WordPlate and the framework. I would grateful for any feedback and suggestions!
