### ISSUE TITLE
getting started questions

### ISSUE THREAD

**Issue by sandrodz** [wordplate/wordplate#174]
Hi,

Migrating from bedrock, have some getting started questions:

1. Why WordPress is not in composer.json from the start? as per docs added wp to require and did composer update. But this seems redundant, if I'm using wordplate means I do want to version wp.
2. Why is not plate plugin autoloaded by default? framework comes with wordplate theme that uses it, so why not just autoload it also? also manually installing autoloader is another extra that seems unnecessary.
3. Is there a way to disable wordpress auto-update and notices? This is a must if I want to keep it under composer.
4. Are mu-plugins updatable by user?

I will post more questions as they arise, first project with WordPlate is underway :) Loving laravel helpers.

**Comment by vinkla** [comment]
Hey @sandrodz, we're glad you're trying WordPlate!

> 1. Why WordPress is not in composer.json from the start? as per docs added wp to require and did composer update. But this seems redundant, if I'm using wordplate means I do want to version wp.

The main reason is that most of the users of WordPlate want to use the latest version of WordPress. Though, it is possible to install an older bugfix release of WordPress if anyone wants too. We don't keep it in the `composer.json` file since we want to keep it clean. This hasn't come up before to be honest. Would you prefer it to be specified in the `composer.json` file by default?

> 2. Why is not plate plugin autoloaded by default? framework comes with wordplate theme that uses it, so why not just autoload it also? also manually installing autoloader is another extra that seems unnecessary.

I see your point. This would mean we need to automagically install the [`autoloader`](https://github.com/wordplate/autoloader) package and require `plate` as a must use plugin. Basically we don't want to enforce the `plate` plugin if the developer doesn't want it.

We've also discussed installing the autoloader package by default. We haven't decided yet though.

> 3. Is there a way to disable wordpress auto-update and notices? This is a must if I want to keep it under composer.

Not right now. We've looked at how other similar libraries does this but haven't implemented anything yet. If you find something we would happily look at pull requests you send our way.

> 4. Are mu-plugins updatable by user?

I don't think so. Not sure though. Maybe @tditlu knows more about this?

> I will post more questions as they arise, first project with WordPlate is underway :) Loving laravel helpers.

Any ideas or feedback you might have are welcome :)
