### ISSUE TITLE
Why not follow WP php conventions?

### ISSUE THREAD

**Issue by sandrodz** [wordplate/wordplate#188]
I usually use convention of the project I'm working in. For WP I use their standards for php e.g. extremely spacious function ( $whatever ) etc.

Why doesn't WordPlate adhere to the same standard?

**Comment by vinkla** [comment]
The team behind WordPlate are coming from building Laravel and Symfony application. We like new PHP standards and want to take advantage of them. We created WordPlate in order to make WordPress easier to work with when you're coming jumping between different PHP projects. We don't agree with the WordPress syntax standard. We want WordPress to update their core and make it installable via Composer. We want them to start being a part of the PHP community. We want them to start using PSR2.
