### ISSUE TITLE
WP_DIR env var is not used in the index file to boot WordPress.

### ISSUE THREAD

**Issue by garhbod** [wordplate/wordplate#241]
I noticed in your framework that there is a `WP_DIR` environment variable but it is not being set in the `public/index.php` file which at this time would have to manually be changed also. Line 37

```
require __DIR__.'/wordpress/wp-blog-header.php';
```

**Comment by vinkla** [comment]
You're right. We could maybe move the creation of the application instance to the `index.php` file. I'll try this locally.

**Comment by vinkla** [comment]
You're right. We'll take a look at any pull request you send our way!

**Comment by vinkla** [comment]
We've decided to not add this programatically since we not sure how it could/should be implemented. We've however [added this to our documentation](https://wordplate.github.io/#/docs/configuration#wordpress-directory). We might revisit this topic in the future. Thanks for opening the issue and sending us a pull request!
