### ISSUE TITLE
Javascript translation not loaded

### ISSUE THREAD

**Issue by DgeDge63** [wordplate/wordplate#246]
Hello everyone,
I have a problem with js translations that are not properly loaded by wordpress. Thanks to the koodimonni-language repository I have all my translations in the `public/languages` folder but the jsons are not loaded correctly. Do you have an idea of the problem and how to fix it?

Thanks for your help.

**Comment by DgeDge63** [comment]
If it can help you in the `load_script_textdomain` function in the `wp-includes/l10n.php` file, the `md5_filename` variable is not the same as the json variable in the "languages" directory and the $languages_path variable is not the right one either.

**Comment by vinkla** [comment]
Hi, I will redirect this question to @fiskhandlarn who knows more about the language system in WordPress.

**Comment by fiskhandlarn** [comment]
@DgeDge63 What do you mean by "jsons"? Are you not using `.mo`/`.po` files in `public/languages`? 

Eitherway, if you've configed `koodimonni-language` in your `composer.json` the languages should be installed automatically with composer, like in https://github.com/fiskhandlarn/lorica/blob/master/composer.json:

```json
{
  "require": {
    "koodimonni-language/core-sv_se": "^5.2"
  },
  "extra": {
    "dropin-paths": {
      "public/languages/": [
        "vendor:koodimonni-language"
      ]
    }
  }
}
```

**Comment by DgeDge63** [comment]
Hello @fiskhandlarn and thank you for your answer.
I use .mo/.po files but for javascript features such as Gutenberg these files are transformed into json. The files are present but are not correctly recovered by wordpress. I have the translations of the back-office but not the one of Gutenberg.

**Comment by fiskhandlarn** [comment]
@DgeDge63 Ah, alright. I've never tried this with Gutenberg, so I'm not sure I can help you. I would suggest digging into if the files are actually linked/included in the html and if not find what needs to be enqueued (I'm guessing with `wp_enqueue_script`).

**Comment by Grafikart** [comment]
Sorry for reopening an old issue but I may have a clue for the problem

## Problem 

Some translations are not loaded correctly in gutenberg and various places

## Clue 

Wordpress uses md5 to load JSON files for some front end translations with this line in the file `i10n.php`.

```php
$md5_filename = $file_base . '-' . md5( $relative ) . '.json';
```

The problem is the $relative variable that is not resolved correctly : 

- Original Wordpress : "wp-includes/js/dist/blocks.js"
- My Wordplate Installation : "js/dist/blocks.js"

This change create a missmatch with the md5 expected from WordPress.

## Clue 2

When resolving where to find the languages it looks in the directory `/public/languages/wordpress` instead of `/public/languages`

## My solution 

This is a "ugly temporary fix", but a fix could be find within the wordplate installation.

```php
// We fix the relative path to fix the md5.
add_filter('load_script_textdomain_relative_path', function ($relative) {
   if (strpos($relative, 'js/') === 0) {
       return 'wp-includes/' . $relative;
   }
   return $relative;
}, 10, 2);

// We fix the path where wordpress is looking for when resolving JSON translations.
add_filter('load_script_translation_file', function ($file) {
    return str_replace('languages/wordpress', 'languages', $file);
}, 100);
```
