### ISSUE TITLE
Disable WordPress Auto Updates

### ISSUE THREAD

**Issue by vinkla** [wordplate/wordplate#96]
```php
// Disable all automatic updates.
define('AUTOMATIC_UPDATER_DISABLED', true);
```

http://codex.wordpress.org/Editing_wp-config.php#Disable_WordPress_Auto_Updates

**Comment by vinkla** [comment]
As I've learned this is quite dangerous to remove. I'll close this for now.

**Comment by badevilerror** [comment]
Why is this not disabled (all automatic updates)? What about composer? Isn't it going to make composer.json out of sync if wordpress updates it self on it's onw?

**Comment by vinkla** [comment]
I recommend using the [`hide-update`](https://wordpress.org/plugins/hide-updates) plugin for this.

**Comment by fiskhandlarn** [comment]
@badevilerror `WP_AUTO_UPDATE_CORE` is already set to `'minor'` by WordPlate. This is the recommended setting (so that WordPress still does security updates, which are important). The automatic minor updates will of course put composer out of sync but it shouldn't break anything. And as long as you update composer on a regular basis this won't really be a problem, IMO.
